version: "3.8"

services:
  # Database - Mongo DB
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: client
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: localdb
    ports:
      - "27017:27017"
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  # Database Manager
  # mongo-express:
  #   image: mongo-express
  #   ports:
  #     - 8099:8081
  #   depends_on:
  #     - mongo
  #   environment:
  #     ME_CONFIG_BASICAUTH_USERNAME: client
  #     ME_CONFIG_BASICAUTH_PASSWORD: password
  #     ME_CONFIG_MONGODB_PORT: 27017
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: client
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: password
  #   links:
  #     - mongo
