services:
  catalogDb:
    image: mysql
    container_name: catalogDb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: api
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: catalogDb

  OrdersDb:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    container_name: OrdersDb
    restart: always
    ports:
      - 1433:1433

  # term:
  #   Optional container to provide a workstation within the cluster
  #   #CMD -> docker exec -it term /bin/sh
  #   build: ./terminal
  #   image: term
  #   tty: true
  #   container_name: term

  catalogApi:
    build: ./catalogApi
    image: catalogapi
    container_name: catalogApi
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - catalogDb

  ordersApi:
    build:
      context: ./OrdersApi
      dockerfile: ./OrdersAPI/Dockerfile
    image: ordersapi
    container_name: ordersApi
    ports:
      - "8000:80"
    depends_on:
      - OrdersDb
