services:
  catalogdb:
    image: mysql
    container_name: catalogdb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: api
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: catalogDb

  ordersdb:
    image: "mcr.microsoft.com/mssql/server"
    container_name: ordersdb
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - 1433:1433

  # term:
  #   Optional container to provide a workstation within the cluster
  #   #CMD -> docker exec -it term /bin/sh
  #   build: ./terminal
  #   image: term
  #   tty: true
  #   container_name: term

  catalogapi:
    build: ./catalogApi
    container_name: catalogapi
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - catalogdb

  ordersapi:
    build:
      context: ./OrdersApi
      dockerfile: ./OrdersAPI/Dockerfile
    container_name: ordersapi
    environment:
      - DOTNET_ENVIRONMENT=DockerDeploy
    ports:
      - "8000:80"
    depends_on:
      - ordersdb
