services:
  catalogDb:
    image: mysql
    container_name: catalogDb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: api
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: catalogDb

  # term:
  #   #docker exec -it term /bin/sh
  #   build: ./terminal
  #   image: term
  #   tty: true
  #   container_name: term

  catalogApi:
    build: ./catalogApi
    image: catalogapi
    container_name: catalogApi
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - catalogDb
