services:
  # standard images
  catalogdb:
    image: mysql
    container_name: catalogdb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: api
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: catalogDb

  ordersdb:
    image: "mcr.microsoft.com/mssql/server"
    container_name: ordersdb
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - 1433:1433

  quotesdb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017

  #Optional container for mongo visibility
  #CMD -> http://localhost:8081
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@quotesdb:27017/
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true

  #Optional container to provide a workstation within the cluster
  #CMD -> docker exec -it term /bin/sh
  # term:

  # build: ./terminal
  # image: term
  # tty: true
  # container_name: term

  # custom images
  catalogapi:
    build: ../APIcatalog
    container_name: catalogapi
    image: suchcodewow/dbic-catalogapi
    restart: always
    ports:
      - 8080:80
    depends_on:
      - catalogdb

  ordersapi:
    build:
      context: ../APIorders
      dockerfile: ./OrdersAPI/Dockerfile
    image: suchcodewow/dbic-ordersapi
    container_name: ordersapi
    environment:
      - DOTNET_ENVIRONMENT=DockerDeploy
    ports:
      - "8000:80"
    depends_on:
      - ordersdb

  quotesapi:
    build:
      context: ../APIquotes
      dockerfile: Dockerfile
    image: suchcodewow/dbic-quotesapi
    container_name: quotesapi
    restart: always
    ports:
      - 6000:80
    depends_on:
      - quotesdb

  ui:
    build: ../UI
    image: suchcodewow/dbic-frontend
    container_name: frontend
    ports:
      - 80:3000
    depends_on:
      - ordersapi
      - catalogapi
